#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurkyeCenter
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="turkyaCenter")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void Insertcustomer(customer instance);
    partial void Updatecustomer(customer instance);
    partial void Deletecustomer(customer instance);
    partial void Insertdress(dress instance);
    partial void Updatedress(dress instance);
    partial void Deletedress(dress instance);
    #endregion
		
		public dbDataContext() : 
				base(global::TurkyeCenter.Properties.Settings.Default.turkyaCenterConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<customer> customers
		{
			get
			{
				return this.GetTable<customer>();
			}
		}
		
		public System.Data.Linq.Table<coat> coats
		{
			get
			{
				return this.GetTable<coat>();
			}
		}
		
		public System.Data.Linq.Table<dress> dresses
		{
			get
			{
				return this.GetTable<dress>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPusers")]
		public ISingleResult<SPusersResult> SPusers([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> choice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, username, password, choice);
			return ((ISingleResult<SPusersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPcoats")]
		public ISingleResult<SPcoatsResult> SPcoats([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> tall, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> shoulder, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> hand, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> chest, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> abdomen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string details, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> customer_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> choice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, tall, shoulder, hand, chest, abdomen, details, date, customer_id, choice);
			return ((ISingleResult<SPcoatsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPdress")]
		public ISingleResult<SPdressResult> SPdress([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> tall, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> shoulder, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> hand1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> hand2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> hand3, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> neck, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> chest, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gbzor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> dwor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string details, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> customer_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> choice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, tall, shoulder, hand1, hand2, hand3, neck, chest, gbzor, dwor, details, date, customer_id, choice);
			return ((ISingleResult<SPdressResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPcustomers")]
		public ISingleResult<SPcustomersResult> SPcustomers([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> choice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, phone, address, choice);
			return ((ISingleResult<SPcustomersResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customers")]
	public partial class customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private System.Nullable<int> _phone;
		
		private string _address;
		
		private EntitySet<dress> _dresses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnphoneChanging(System.Nullable<int> value);
    partial void OnphoneChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    #endregion
		
		public customer()
		{
			this._dresses = new EntitySet<dress>(new Action<dress>(this.attach_dresses), new Action<dress>(this.detach_dresses));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="Int")]
		public System.Nullable<int> phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_dress", Storage="_dresses", ThisKey="id", OtherKey="customer_id")]
		public EntitySet<dress> dresses
		{
			get
			{
				return this._dresses;
			}
			set
			{
				this._dresses.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dresses(dress entity)
		{
			this.SendPropertyChanging();
			entity.customer = this;
		}
		
		private void detach_dresses(dress entity)
		{
			this.SendPropertyChanging();
			entity.customer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.coats")]
	public partial class coat
	{
		
		private int _id;
		
		private System.Nullable<double> _tall;
		
		private System.Nullable<double> _shoulder;
		
		private System.Nullable<double> _hand;
		
		private System.Nullable<double> _chest;
		
		private System.Nullable<double> _abdomen;
		
		private string _details;
		
		private string _date;
		
		private System.Nullable<int> _customer_id;
		
		public coat()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tall", DbType="Float")]
		public System.Nullable<double> tall
		{
			get
			{
				return this._tall;
			}
			set
			{
				if ((this._tall != value))
				{
					this._tall = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shoulder", DbType="Float")]
		public System.Nullable<double> shoulder
		{
			get
			{
				return this._shoulder;
			}
			set
			{
				if ((this._shoulder != value))
				{
					this._shoulder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hand", DbType="Float")]
		public System.Nullable<double> hand
		{
			get
			{
				return this._hand;
			}
			set
			{
				if ((this._hand != value))
				{
					this._hand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chest", DbType="Float")]
		public System.Nullable<double> chest
		{
			get
			{
				return this._chest;
			}
			set
			{
				if ((this._chest != value))
				{
					this._chest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abdomen", DbType="Float")]
		public System.Nullable<double> abdomen
		{
			get
			{
				return this._abdomen;
			}
			set
			{
				if ((this._abdomen != value))
				{
					this._abdomen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_details", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string details
		{
			get
			{
				return this._details;
			}
			set
			{
				if ((this._details != value))
				{
					this._details = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_id", DbType="Int")]
		public System.Nullable<int> customer_id
		{
			get
			{
				return this._customer_id;
			}
			set
			{
				if ((this._customer_id != value))
				{
					this._customer_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dress")]
	public partial class dress : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<double> _tall;
		
		private System.Nullable<double> _shoulder;
		
		private System.Nullable<double> _hand1;
		
		private System.Nullable<double> _hand2;
		
		private System.Nullable<double> _hand3;
		
		private System.Nullable<double> _neck;
		
		private System.Nullable<double> _chest;
		
		private System.Nullable<double> _gbzor;
		
		private System.Nullable<double> _dwor;
		
		private string _details;
		
		private string _date;
		
		private System.Nullable<int> _customer_id;
		
		private EntityRef<customer> _customer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntallChanging(System.Nullable<double> value);
    partial void OntallChanged();
    partial void OnshoulderChanging(System.Nullable<double> value);
    partial void OnshoulderChanged();
    partial void Onhand1Changing(System.Nullable<double> value);
    partial void Onhand1Changed();
    partial void Onhand2Changing(System.Nullable<double> value);
    partial void Onhand2Changed();
    partial void Onhand3Changing(System.Nullable<double> value);
    partial void Onhand3Changed();
    partial void OnneckChanging(System.Nullable<double> value);
    partial void OnneckChanged();
    partial void OnchestChanging(System.Nullable<double> value);
    partial void OnchestChanged();
    partial void OngbzorChanging(System.Nullable<double> value);
    partial void OngbzorChanged();
    partial void OndworChanging(System.Nullable<double> value);
    partial void OndworChanged();
    partial void OndetailsChanging(string value);
    partial void OndetailsChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void Oncustomer_idChanging(System.Nullable<int> value);
    partial void Oncustomer_idChanged();
    #endregion
		
		public dress()
		{
			this._customer = default(EntityRef<customer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tall", DbType="Float")]
		public System.Nullable<double> tall
		{
			get
			{
				return this._tall;
			}
			set
			{
				if ((this._tall != value))
				{
					this.OntallChanging(value);
					this.SendPropertyChanging();
					this._tall = value;
					this.SendPropertyChanged("tall");
					this.OntallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shoulder", DbType="Float")]
		public System.Nullable<double> shoulder
		{
			get
			{
				return this._shoulder;
			}
			set
			{
				if ((this._shoulder != value))
				{
					this.OnshoulderChanging(value);
					this.SendPropertyChanging();
					this._shoulder = value;
					this.SendPropertyChanged("shoulder");
					this.OnshoulderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hand1", DbType="Float")]
		public System.Nullable<double> hand1
		{
			get
			{
				return this._hand1;
			}
			set
			{
				if ((this._hand1 != value))
				{
					this.Onhand1Changing(value);
					this.SendPropertyChanging();
					this._hand1 = value;
					this.SendPropertyChanged("hand1");
					this.Onhand1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hand2", DbType="Float")]
		public System.Nullable<double> hand2
		{
			get
			{
				return this._hand2;
			}
			set
			{
				if ((this._hand2 != value))
				{
					this.Onhand2Changing(value);
					this.SendPropertyChanging();
					this._hand2 = value;
					this.SendPropertyChanged("hand2");
					this.Onhand2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hand3", DbType="Float")]
		public System.Nullable<double> hand3
		{
			get
			{
				return this._hand3;
			}
			set
			{
				if ((this._hand3 != value))
				{
					this.Onhand3Changing(value);
					this.SendPropertyChanging();
					this._hand3 = value;
					this.SendPropertyChanged("hand3");
					this.Onhand3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_neck", DbType="Float")]
		public System.Nullable<double> neck
		{
			get
			{
				return this._neck;
			}
			set
			{
				if ((this._neck != value))
				{
					this.OnneckChanging(value);
					this.SendPropertyChanging();
					this._neck = value;
					this.SendPropertyChanged("neck");
					this.OnneckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chest", DbType="Float")]
		public System.Nullable<double> chest
		{
			get
			{
				return this._chest;
			}
			set
			{
				if ((this._chest != value))
				{
					this.OnchestChanging(value);
					this.SendPropertyChanging();
					this._chest = value;
					this.SendPropertyChanged("chest");
					this.OnchestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gbzor", DbType="Float")]
		public System.Nullable<double> gbzor
		{
			get
			{
				return this._gbzor;
			}
			set
			{
				if ((this._gbzor != value))
				{
					this.OngbzorChanging(value);
					this.SendPropertyChanging();
					this._gbzor = value;
					this.SendPropertyChanged("gbzor");
					this.OngbzorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dwor", DbType="Float")]
		public System.Nullable<double> dwor
		{
			get
			{
				return this._dwor;
			}
			set
			{
				if ((this._dwor != value))
				{
					this.OndworChanging(value);
					this.SendPropertyChanging();
					this._dwor = value;
					this.SendPropertyChanged("dwor");
					this.OndworChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_details", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string details
		{
			get
			{
				return this._details;
			}
			set
			{
				if ((this._details != value))
				{
					this.OndetailsChanging(value);
					this.SendPropertyChanging();
					this._details = value;
					this.SendPropertyChanged("details");
					this.OndetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_id", DbType="Int")]
		public System.Nullable<int> customer_id
		{
			get
			{
				return this._customer_id;
			}
			set
			{
				if ((this._customer_id != value))
				{
					if (this._customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncustomer_idChanging(value);
					this.SendPropertyChanging();
					this._customer_id = value;
					this.SendPropertyChanged("customer_id");
					this.Oncustomer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_dress", Storage="_customer", ThisKey="customer_id", OtherKey="id", IsForeignKey=true)]
		public customer customer
		{
			get
			{
				return this._customer.Entity;
			}
			set
			{
				customer previousValue = this._customer.Entity;
				if (((previousValue != value) 
							|| (this._customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._customer.Entity = null;
						previousValue.dresses.Remove(this);
					}
					this._customer.Entity = value;
					if ((value != null))
					{
						value.dresses.Add(this);
						this._customer_id = value.id;
					}
					else
					{
						this._customer_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("customer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SPusersResult
	{
		
		private int _id;
		
		private string _username;
		
		private string _password;
		
		public SPusersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
	}
	
	public partial class SPcoatsResult
	{
		
		private int _id;
		
		private System.Nullable<double> _tall;
		
		private System.Nullable<double> _shoulder;
		
		private System.Nullable<double> _hand;
		
		private System.Nullable<double> _chest;
		
		private System.Nullable<double> _abdomen;
		
		private string _details;
		
		private string _date;
		
		private System.Nullable<int> _customer_id;
		
		public SPcoatsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tall", DbType="Float")]
		public System.Nullable<double> tall
		{
			get
			{
				return this._tall;
			}
			set
			{
				if ((this._tall != value))
				{
					this._tall = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shoulder", DbType="Float")]
		public System.Nullable<double> shoulder
		{
			get
			{
				return this._shoulder;
			}
			set
			{
				if ((this._shoulder != value))
				{
					this._shoulder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hand", DbType="Float")]
		public System.Nullable<double> hand
		{
			get
			{
				return this._hand;
			}
			set
			{
				if ((this._hand != value))
				{
					this._hand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chest", DbType="Float")]
		public System.Nullable<double> chest
		{
			get
			{
				return this._chest;
			}
			set
			{
				if ((this._chest != value))
				{
					this._chest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abdomen", DbType="Float")]
		public System.Nullable<double> abdomen
		{
			get
			{
				return this._abdomen;
			}
			set
			{
				if ((this._abdomen != value))
				{
					this._abdomen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_details", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string details
		{
			get
			{
				return this._details;
			}
			set
			{
				if ((this._details != value))
				{
					this._details = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_id", DbType="Int")]
		public System.Nullable<int> customer_id
		{
			get
			{
				return this._customer_id;
			}
			set
			{
				if ((this._customer_id != value))
				{
					this._customer_id = value;
				}
			}
		}
	}
	
	public partial class SPdressResult
	{
		
		private int _id;
		
		private System.Nullable<double> _tall;
		
		private System.Nullable<double> _shoulder;
		
		private System.Nullable<double> _hand1;
		
		private System.Nullable<double> _hand2;
		
		private System.Nullable<double> _hand3;
		
		private System.Nullable<double> _neck;
		
		private System.Nullable<double> _chest;
		
		private System.Nullable<double> _gbzor;
		
		private System.Nullable<double> _dwor;
		
		private string _details;
		
		private string _date;
		
		private System.Nullable<int> _customer_id;
		
		public SPdressResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tall", DbType="Float")]
		public System.Nullable<double> tall
		{
			get
			{
				return this._tall;
			}
			set
			{
				if ((this._tall != value))
				{
					this._tall = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shoulder", DbType="Float")]
		public System.Nullable<double> shoulder
		{
			get
			{
				return this._shoulder;
			}
			set
			{
				if ((this._shoulder != value))
				{
					this._shoulder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hand1", DbType="Float")]
		public System.Nullable<double> hand1
		{
			get
			{
				return this._hand1;
			}
			set
			{
				if ((this._hand1 != value))
				{
					this._hand1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hand2", DbType="Float")]
		public System.Nullable<double> hand2
		{
			get
			{
				return this._hand2;
			}
			set
			{
				if ((this._hand2 != value))
				{
					this._hand2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hand3", DbType="Float")]
		public System.Nullable<double> hand3
		{
			get
			{
				return this._hand3;
			}
			set
			{
				if ((this._hand3 != value))
				{
					this._hand3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_neck", DbType="Float")]
		public System.Nullable<double> neck
		{
			get
			{
				return this._neck;
			}
			set
			{
				if ((this._neck != value))
				{
					this._neck = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chest", DbType="Float")]
		public System.Nullable<double> chest
		{
			get
			{
				return this._chest;
			}
			set
			{
				if ((this._chest != value))
				{
					this._chest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gbzor", DbType="Float")]
		public System.Nullable<double> gbzor
		{
			get
			{
				return this._gbzor;
			}
			set
			{
				if ((this._gbzor != value))
				{
					this._gbzor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dwor", DbType="Float")]
		public System.Nullable<double> dwor
		{
			get
			{
				return this._dwor;
			}
			set
			{
				if ((this._dwor != value))
				{
					this._dwor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_details", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string details
		{
			get
			{
				return this._details;
			}
			set
			{
				if ((this._details != value))
				{
					this._details = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_id", DbType="Int")]
		public System.Nullable<int> customer_id
		{
			get
			{
				return this._customer_id;
			}
			set
			{
				if ((this._customer_id != value))
				{
					this._customer_id = value;
				}
			}
		}
	}
	
	public partial class SPcustomersResult
	{
		
		private int _id;
		
		private string _name;
		
		private System.Nullable<int> _phone;
		
		private string _address;
		
		public SPcustomersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="Int")]
		public System.Nullable<int> phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
